using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Xunit;

namespace FanaBridge.Tests.Display.Replay
{
    /// <summary>
    /// E8 round 3: full-system replay parity harness over the closed matrix.
    /// Comparison = ordered attempted col01+col03 write streams at the transport seam;
    /// sole normalization = PageSet-retry timing jitter. Engine bugs are recorded as
    /// SkippableFact skips with E8-PARITY-XX ids — src is never patched this round.
    /// </summary>
    [Collection(ReplayParityCollection.Name)]
    public class EngineReplayTests
    {
        public EngineReplayTests()
        {
            // Pin on the test thread (collection fixture also pins; belt-and-braces for
            // adjudication MINOR residual determinism).
            CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;
            CultureInfo.CurrentUICulture = CultureInfo.InvariantCulture;
        }

        // ── Matrix inventory ─────────────────────────────────────────────

        [Fact]
        public void Matrix_EnumeratesClosedBudget_AndLogsAxes()
        {
            var all = ReplayMatrix.All();
            Assert.NotEmpty(all);

            int anchored = all.Count(c => c.Block == ReplayBlock.Anchored);
            int pairwise = all.Count(c => c.Block == ReplayBlock.Pairwise);
            int kept = all.Count(c => c.Block == ReplayBlock.KeptBehavior);
            int hyst = all.Count(c => c.Block == ReplayBlock.Hysteresis);
            int unrep = all.Count(c => !c.IsRepresentable);

            // OQ-5 full budget: ~95 + hysteresis block. Allow the documented ±20.
            Assert.True(all.Count >= 70, "matrix too small: " + all.Count);
            Assert.True(all.Count <= 130, "matrix exploded: " + all.Count);
            Assert.True(anchored >= 20, "anchored OFAT under-covered: " + anchored);
            Assert.True(pairwise >= 30, "pairwise under-covered: " + pairwise);
            Assert.True(kept >= 15, "kept-behavior under-covered: " + kept);
            Assert.True(hyst >= 6, "hysteresis block missing operators: " + hyst);

            // ActionTriggered must never appear (FA2 / adjudication).
            Assert.DoesNotContain(all, c =>
                c.Id.IndexOf("actiontriggered", StringComparison.OrdinalIgnoreCase) >= 0
                || c.Id.IndexOf("action-triggered", StringComparison.OrdinalIgnoreCase) >= 0);

            // Game-start kept cell in every device column (RISK-5).
            foreach (ReplayDevice d in Enum.GetValues(typeof(ReplayDevice)))
            {
                Assert.Contains(all, c =>
                    c.Block == ReplayBlock.KeptBehavior
                    && c.Device == d
                    && c.KeptBehaviorName == "game-start-manual-reset");
            }

            // Every cell logs axes; unrepresentable cells keep a reason (no silent drops).
            var report = new StringBuilder();
            report.AppendLine(string.Format(
                CultureInfo.InvariantCulture,
                "E8 matrix: total={0} anchored={1} pairwise={2} kept={3} hysteresis={4} unrepresentable={5}",
                all.Count, anchored, pairwise, kept, hyst, unrep));
            foreach (var c in all)
            {
                report.AppendLine(c.AxesLog
                    + (c.IsRepresentable ? "" : " UNREPRESENTABLE=" + c.UnrepresentableReason));
            }

            // Write inventory next to fixtures for the human report.
            string dir = ReplayFixtureFactory.FixturesDirectory();
            Directory.CreateDirectory(dir);
            File.WriteAllText(
                Path.Combine(dir, "_matrix-inventory.txt"),
                report.ToString(),
                Encoding.UTF8);

            Assert.True(unrep == all.Count(c => c.UnrepresentableReason != null));
        }

        [Fact]
        public void Matrix_MaterializesFixturePairs()
        {
            var representable = ReplayMatrix.All().Where(c => c.IsRepresentable).ToList();
            ReplayFixtureFactory.MaterializeAll(representable);

            string dir = ReplayFixtureFactory.FixturesDirectory();
            // FR-9: every committed pair must equal freshly generated bytes (no stale-disk).
            foreach (var cell in representable)
            {
                var (v1Gen, v2Gen) = ReplayFixtureFactory.BuildPair(cell);
                string v1Path = Path.Combine(dir, cell.Id + ".v1.json");
                string v2Path = Path.Combine(dir, cell.Id + ".v2.json");
                Assert.True(File.Exists(v1Path), cell.Id + ".v1.json missing");
                Assert.True(File.Exists(v2Path), cell.Id + ".v2.json missing");
                Assert.Equal(v1Gen, File.ReadAllText(v1Path));
                Assert.Equal(v2Gen, File.ReadAllText(v2Path));
            }

            // Spot-check: no ActionTriggered in any v1 fixture content sample.
            string sample = File.ReadAllText(
                Path.Combine(dir, representable[0].Id + ".v1.json"));
            Assert.DoesNotContain("actionTriggered", sample);
        }

        // ── Isolation / culture plumbing ─────────────────────────────────

        [Fact]
        public void Isolation_DistinctTransports_AndInvariantCulturePinned()
        {
            Assert.Equal(CultureInfo.InvariantCulture, CultureInfo.CurrentCulture);
            Assert.Equal(CultureInfo.InvariantCulture, CultureInfo.CurrentUICulture);

            var cell = ReplayMatrix.All().First(c =>
                c.IsRepresentable
                && c.Device == ReplayDevice.Pbme
                && c.Block == ReplayBlock.Anchored
                && c.Target == ReplayTarget.Page
                && c.Condition == ReplayCondition.GreaterThan
                && c.Press == ReplayPress.None
                && c.Wire == ReplayWire.Clean);

            var (v9, v2) = ReplayHarness.RunPair(cell);
            // Both engines produced some wire activity on a clean ITM bring-up.
            Assert.NotEmpty(v9);
            Assert.NotEmpty(v2);
            // Recorder defensive-copy: payloads must not be the same array instance.
            if (v9.Count > 0 && v2.Count > 0)
                Assert.False(ReferenceEquals(v9[0].Payload, v2[0].Payload));
        }

        [Fact]
        public void Normalizer_CollapsesDeclinedSetPageRuns()
        {
            // FF 05 04 03 01 — SetPage device 3 page 1
            byte[] page = { 0xFF, 0x05, 0x04, 0x03, 0x01 };
            byte[] other = { 0xFF, 0x05, 0x02, 0x01 }; // EnableItm-shaped

            var raw = new List<WireAttempt>
            {
                new WireAttempt(1, 0, 16, Chan.Col03, page, accepted: false),
                new WireAttempt(2, 0, 32, Chan.Col03, page, accepted: false),
                new WireAttempt(3, 0, 48, Chan.Col03, page, accepted: true),
                new WireAttempt(4, 0, 64, Chan.Col03, other, accepted: true),
            };

            var n = PageSetRetryNormalizer.Normalize(raw);
            Assert.Equal(2, n.Count);
            Assert.True(n[0].Accepted);
            Assert.Equal(1, n[0].FrameIndex); // first frame of run retained
            Assert.True(WireAttempt.PayloadBytesEqual(other, n[1].Payload));
        }

        /// <summary>
        /// H5: on lifecycle recovery the v2 reconnect burst must command SetPage before
        /// the first col01 face write (v9 cold-entry ordering). Hosted-only page-policy
        /// decline is unchanged in steady state; only the recovery burst ordering aligns.
        /// </summary>
        [Fact]
        public void LifecycleRecovery_V2_SetPagePrecedesFirstCol01FaceInReconnectBurst()
        {
            var cell = ReplayMatrix.ById(
                "e8-pbme-segment-screen-greater-than-for-duration-in-game-known-page-none-lifecycle-recovery");
            Assert.True(cell.IsRepresentable);
            Assert.Equal(ReplayWire.LifecycleRecovery, cell.Wire);

            var (_, v2) = ReplayHarness.RunPair(cell);
            // Second DisplayReset (FF 05 05 01) opens the reconnect bring-up burst.
            int reconnect = -1;
            int resets = 0;
            for (int i = 0; i < v2.Count; i++)
            {
                if (v2[i].Channel != Chan.Col03 || v2[i].Payload.Length < 3)
                    continue;
                if (v2[i].Payload[0] == 0xFF && v2[i].Payload[1] == 0x05
                    && v2[i].Payload[2] == 0x05)
                {
                    resets++;
                    if (resets == 2)
                    {
                        reconnect = i;
                        break;
                    }
                }
            }
            Assert.True(reconnect >= 0, "v2 stream missing reconnect DisplayReset");

            int setPage = -1;
            int col01 = -1;
            for (int i = reconnect; i < v2.Count; i++)
            {
                if (setPage < 0 && PageSetRetryNormalizer.IsSetPage(v2[i].Payload))
                    setPage = i;
                if (col01 < 0 && v2[i].Channel == Chan.Col01)
                    col01 = i;
                if (setPage >= 0 && col01 >= 0)
                    break;
            }

            Assert.True(setPage >= 0, "v2 reconnect burst missing SetPage");
            Assert.True(col01 >= 0, "v2 reconnect burst missing col01 face write");
            Assert.True(setPage < col01,
                "H5: recovery SetPage must precede first col01 face paint (setPage@ "
                + setPage + " col01@ " + col01 + ")");
            Assert.Equal(v2[reconnect].FrameIndex, v2[setPage].FrameIndex);
        }

        // ── Per-cell parity theory ───────────────────────────────────────

        public static IEnumerable<object[]> RepresentableCellIds()
            => ReplayMatrix.All()
                .Where(c => c.IsRepresentable)
                .Select(c => new object[] { c.Id });

        public static IEnumerable<object[]> UnrepresentableCellIds()
            => ReplayMatrix.All()
                .Where(c => !c.IsRepresentable)
                .Select(c => new object[] { c.Id, c.UnrepresentableReason! });

        [Theory]
        [MemberData(nameof(UnrepresentableCellIds))]
        public void Unrepresentable_Cells_AreReportedNotSilent(string id, string reason)
        {
            Assert.False(string.IsNullOrWhiteSpace(id));
            Assert.False(string.IsNullOrWhiteSpace(reason));
            var cell = ReplayMatrix.ById(id);
            Assert.False(cell.IsRepresentable);
            Assert.Equal(reason, cell.UnrepresentableReason);
            // Axes still logged.
            Assert.Contains(id, cell.AxesLog, StringComparison.Ordinal);
        }

        [Theory]
        [MemberData(nameof(RepresentableCellIds))]
        public void Parity_Cell(string cellId)
        {
            var cell = ReplayMatrix.ById(cellId);
            Assert.True(cell.IsRepresentable, cell.UnrepresentableReason);

            StreamComparer.Result result;
            try
            {
                result = ReplayHarness.RunAndCompare(cell);
            }
            catch (Exception ex)
            {
                string msg = "E8-PARITY-HARNESS: " + cellId + " — " + ex.GetType().Name
                    + ": " + ex.Message;
                throw new Xunit.Sdk.XunitException(msg + Environment.NewLine + ex);
            }

            if (!result.Passed)
            {
                string dir = ReplayFixtureFactory.FixturesDirectory();
                Directory.CreateDirectory(dir);
                File.WriteAllText(
                    Path.Combine(dir, cellId + ".diff.txt"),
                    result.Failure ?? "stream mismatch",
                    Encoding.UTF8);
            }

            Assert.True(result.Passed,
                cellId + Environment.NewLine + (result.Failure ?? "stream mismatch")
                + Environment.NewLine + "summary: " + (SummarizeDivergence(result) ?? "-"));
        }

        /// <summary>One-line cause from the first diverging pair (channel + short hex).</summary>
        private static string? SummarizeDivergence(StreamComparer.Result result)
        {
            var v9 = result.V9;
            var v2 = result.V2;
            int n = Math.Min(v9.Count, v2.Count);
            for (int i = 0; i < n; i++)
            {
                if (v9[i].Channel == v2[i].Channel
                    && v9[i].Accepted == v2[i].Accepted
                    && WireAttempt.PayloadBytesEqual(v9[i].Payload, v2[i].Payload))
                    continue;
                return string.Format(
                    CultureInfo.InvariantCulture,
                    "at[{0}] v9={1}/{2} v2={3}/{4}",
                    i,
                    v9[i].Channel, ShortHex(v9[i].Payload),
                    v2[i].Channel, ShortHex(v2[i].Payload));
            }
            if (v9.Count != v2.Count)
            {
                return string.Format(
                    CultureInfo.InvariantCulture,
                    "length v9={0} v2={1} (prefix matched {2})",
                    v9.Count, v2.Count, n);
            }
            return null;
        }

        private static string ShortHex(byte[] p)
        {
            if (p == null || p.Length == 0)
                return "-";
            int take = Math.Min(p.Length, 6);
            return BitConverter.ToString(p, 0, take) + (p.Length > take ? "…" : "");
        }

    }

    /// <summary>
    /// Unit tests for the stream comparer / known-diff consumption (no device session).
    /// </summary>
    [Collection(ReplayParityCollection.Name)]
    public class StreamComparerTests
    {
        public StreamComparerTests()
        {
            CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;
            CultureInfo.CurrentUICulture = CultureInfo.InvariantCulture;
        }

        [Fact]
        public void Compare_IdenticalStreams_Pass()
        {
            byte[] p = { 1, 2, 3 };
            var a = new[]
            {
                new WireAttempt(0, 0, 0, Chan.Col01, p, true),
                new WireAttempt(1, 0, 16, Chan.Col03, p, true),
            };
            var r = StreamComparer.Compare(a, a);
            Assert.True(r.Passed, r.Failure);
        }

        [Fact]
        public void Compare_UnknownDiff_Fails()
        {
            var v9 = new[] { new WireAttempt(0, 0, 0, Chan.Col01, new byte[] { 1 }, true) };
            var v2 = new[] { new WireAttempt(0, 0, 0, Chan.Col01, new byte[] { 2 }, true) };
            var r = StreamComparer.Compare(v9, v2);
            Assert.False(r.Passed);
            Assert.Contains("mismatch", r.Failure!, StringComparison.OrdinalIgnoreCase);
        }

        [Fact]
        public void Compare_NamedKnownDiff_Consumes()
        {
            var v9 = new[] { new WireAttempt(5, 0, 80, Chan.Col03, new byte[] { 0xAA }, true) };
            var v2 = new[] { new WireAttempt(5, 0, 80, Chan.Col03, new byte[] { 0xBB }, true) };
            var diffs = new[]
            {
                new KnownDiff("suffix-blink", 5, Chan.Col03, new byte[] { 0xAA }, new byte[] { 0xBB }),
            };
            var r = StreamComparer.Compare(v9, v2, diffs);
            Assert.True(r.Passed, r.Failure);
        }

        [Fact]
        public void Compare_UnconsumedKnownDiff_Fails()
        {
            var a = new[] { new WireAttempt(0, 0, 0, Chan.Col01, new byte[] { 1 }, true) };
            var diffs = new[]
            {
                new KnownDiff("never-happened", 9, Chan.Col03, new byte[] { 1 }, null),
            };
            var r = StreamComparer.Compare(a, a, diffs);
            Assert.False(r.Passed);
            Assert.Contains("Unconsumed", r.Failure!, StringComparison.Ordinal);
        }

        /// <summary>
        /// Codex probe: named class handlers must not discard an unnamed AA/BB tail
        /// (no prefix-retention / LCP keep / tail truncate).
        /// </summary>
        [Fact]
        public void Compare_AdversarialUnnamedTail_Fails()
        {
            // Shared prefix that would satisfy a class pin (Speed col01), then unnamed tail.
            byte[] speed = ReplayKnownDiffs.Speed142Col01;
            var v9 = new[]
            {
                new WireAttempt(0, 0, 0, Chan.Col01, speed, true),
                new WireAttempt(1, 0, 16, Chan.Col03, new byte[] { 0xAA }, true),
            };
            var v2 = new[]
            {
                new WireAttempt(0, 0, 0, Chan.Col01, speed, true),
                new WireAttempt(1, 0, 16, Chan.Col03, new byte[] { 0xBB }, true),
            };

            // Segment-screen class substitutes the pinned SetPage only; residual AA/BB
            // must fail (would have Passed=True under LCP discard / tail truncate).
            var setPage = ReplayKnownDiffs.SetPageLegacyPbme;
            var v9s = new[]
            {
                new WireAttempt(0, 0, 0, Chan.Col03, setPage, true),
                new WireAttempt(1, 0, 16, Chan.Col03, new byte[] { 0xAA }, true),
            };
            var v2s = new[]
            {
                new WireAttempt(0, 0, 0, Chan.Col03, setPage, true),
                new WireAttempt(1, 0, 16, Chan.Col03, new byte[] { 0xBB }, true),
            };
            var r = StreamComparer.Compare(v9s, v2s, new[]
            {
                ReplayKnownDiffs.SegmentScreenSetPageOrdering,
            });
            Assert.False(r.Passed);
            Assert.Contains("mismatch", r.Failure!, StringComparison.OrdinalIgnoreCase);

            // Blank-idle one-sided class: pin removes blank only — AA/BB tail still fails.
            byte[] blank = { 0x01, 0xF8, 0x09, 0x01, 0x50, 0x00, 0x00, 0x00 };
            var v9b = new[]
            {
                new WireAttempt(0, 0, 0, Chan.Col01, speed, true),
                new WireAttempt(1, 0, 16, Chan.Col03, new byte[] { 0xAA }, true),
            };
            var v2b = new[]
            {
                new WireAttempt(0, 0, 0, Chan.Col01, speed, true),
                new WireAttempt(0, 1, 0, Chan.Col01, blank, true),
                new WireAttempt(1, 0, 16, Chan.Col03, new byte[] { 0xBB }, true),
            };
            var r2 = StreamComparer.Compare(v9b, v2b, new[]
            {
                ReplayKnownDiffs.BlankCompileFirmwareIdle,
            });
            Assert.False(r2.Passed);
            Assert.Contains("mismatch", r2.Failure!, StringComparison.OrdinalIgnoreCase);
        }
    }
}
